using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Chernobyl_Relay_Chat
{
    public class CRCStrings
    {
        private static Random rand = new Random();
        private static string PickRandom(List<string> list)
        {
            return list[rand.Next(list.Count)];
        }

        public static string RandomName(string faction)
        {
            faction = ValidateFaction(faction);
            return PickRandom(fNames[faction]) + " " + PickRandom(sNames[faction]);
        }

        public static string ValidateFaction(string faction)
        {
            return validFactions.Contains(faction) ? faction : "actor_stalker";
        }

        public static string DeathMessage(string name, string level, string xrClass, string section)
        {
            string levelText = levels.ContainsKey(level) ? levels[level] : ("somewhere in the Zone (" + level + ")");
            string deathText;
            if (deathBySection.ContainsKey(section))
                deathText = deathBySection[section];
            else if (deathByClass.ContainsKey(xrClass))
                deathText = deathByClass[xrClass];
            else
                deathText = "died of unknown causes (" + xrClass + "|" + section + ")";

            string message = formats[rand.Next(formats.Count - 1)];
            message = message.Replace("$when", PickRandom(times));
            message = message.Replace("$level", levelText);
            message = message.Replace("$saw", PickRandom(observances));
            message = message.Replace("$name", name);
            message = message.Replace("$death", deathText);
            message = message[0].ToString().ToUpper() + message.Substring(1);
            if (rand.Next(100) >= 75)
                message += ' ' + PickRandom(suffixes);
            return message;
        }

        public static void Populate()
        {
            fNames["actor_csky"] = new List<string>(fNames["actor_stalker"].Concat(fNames["actor_ecolog"]));
            fNames["actor_dolg"] = new List<string>(fNames["actor_stalker"].Concat(fNames["actor_army"]));
            fNames["actor_freedom"] = new List<string>(fNames["actor_stalker"].Concat(fNames["actor_bandit"]));
            fNames["actor_killer"] = new List<string>(fNames["actor_stalker"].Concat(fNames["actor_bandit"]).Concat(fNames["actor_ecolog"]));
            fNames["actor_monolith"] = new List<string>(fNames["actor_stalker"].Concat(fNames["actor_bandit"]).Concat(fNames["actor_ecolog"]));

            sNames["actor_csky"] = new List<string>(sNames["actor_stalker"].Concat(sNames["actor_ecolog"]));
            sNames["actor_dolg"] = new List<string>(sNames["actor_stalker"].Concat(sNames["actor_army"]));
            sNames["actor_freedom"] = new List<string>(sNames["actor_stalker"].Concat(sNames["actor_bandit"]));
            sNames["actor_killer"] = new List<string>(sNames["actor_stalker"].Concat(sNames["actor_bandit"]).Concat(sNames["actor_ecolog"]));
            sNames["actor_monolith"] = new List<string>(sNames["actor_stalker"].Concat(sNames["actor_bandit"]).Concat(sNames["actor_ecolog"]));
        }

        private static List<string> validFactions = new List<string>()
        {
            "actor_bandit",
            "actor_csky",
            "actor_dolg",
            "actor_ecolog",
            "actor_freedom",
            "actor_stalker",
            "actor_killer",
            "actor_army",
            "actor_monolith",
            "actor_zombied",
        };

        private static List<string> formats = new List<string>()
        {
            "$when $level $saw $name $death.",
            "$level $when $saw $name $death.",
            "$level $name $death.",
            "$when $level $name $death.",
            "$saw $level $name $death.",
            "$when $saw $name $death.",
            "$name $death $when $level.",
            "$name $death $level $when.",
            "$when $name $death $level.",
            "$when $name $death.",
            "$when $saw $name $death $level.",
            "$saw $name $death.",
            "$saw $name $death $when $level.",
            "$saw $name $death $level.",
        };

        private static List<string> times = new List<string>()
        {
            "recently",
            "a few minutes ago",
            "just now",
            "a moment ago",
            "just a moment ago",
            "a couple minutes ago",
            "a couple of minutes ago",
            "a short time ago",
            "just recently",
        };

        private static List<string> observances = new List<string>()
        {
            "I saw",
            "I noticed",
            "it seems",
            "someone told me",
            "word is",
            "I've seen",
            "I've noticed",
            "seems",
        };

        private static List<string> suffixes = new List<string>()
        {
            "Good riddance!",
            "What a shame...",
            "He was a good stalker.",
            "Let's drink to him once more!",
            "Damn, he owed me money.",
            "Be careful, friends.",
            "Watch out if you're in the area.",
            "He got what he deserved.",
            "Should have been more careful.",
            "Nasty.",
            "Shit, that could have been me.",
            "I'm getting out of here.",
            "Too bad.",
            "Terrible.",
            "Funny.",
            "Oh well.",
            "Hah!",
            "Hope the info is useful.",
            "He had it coming.",
            "Guess he won't be needing that gear any more...",
            "That's what happens when you let your guard down.",
            "Heh.",
            "Oops!",
            "I never liked him anyways.",
        };

        private static Dictionary<string, string> levels = new Dictionary<string, string>()
        {
            ["k00_marsh"] = "at the Swamps",
            ["k01_darkscape"] = "in Darkscape",
            ["k02_trucks_cemetery"] = "in the Truck Cemetery",
            ["l01_escape"] = "at the Cordon",
            ["l02_garbage"] = "at the Garbage",
            ["l03_agroprom"] = "at Agroprom",
            ["l03u_agr_underground"] = "in Agroprom Underground",
            ["l04_darkvalley"] = "in Dark Valley",
            ["l04u_labx18"] = "in Lab X-18",
            ["l05_bar"] = "at the Bar",
            ["l06_rostok"] = "at Wild Territory",
            ["l07_military"] = "at the Army Warehouses",
            ["l08_yantar"] = "at Lake Yantar",
            ["l08u_brainlab"] = "in Lab X-16",
            ["l09_deadcity"] = "in Dead City",
            ["l10_limansk"] = "in Limansk",
            ["l10_radar"] = "at Radar",
            ["l10_red_forest"] = "in Red Forest",
            ["l10u_bunker"] = "in the Brain Scorcher",
            ["l11_hospital"] = "in the Hospital",
            ["l11_pripyat"] = "in Eastern Pripyat",
            ["l12_stancia"] = "outside the CNPP",
            ["l12_stancia_2"] = "outside the CNPP",
            ["l12u_control_monolith"] = "inside the CNPP",
            ["l12u_sarcofag"] = "inside the CNPP",
            ["l13_generators"] = "at the Generators",
            ["l13u_warlab"] = "in Warlab",
            ["jupiter"] = "around Jupiter",
            ["jupiter_underground"] = "in the Pripyat Underpass",
            ["labx8"] = "in Lab X-8",
            ["pripyat"] = "in Western Pripyat",
            ["zaton"] = "at Zaton",
        };

        private static Dictionary<string, string> deathBySection = new Dictionary<string, string>()
        {

        };

        private static Dictionary<string, string> deathByClass = new Dictionary<string, string>()
        {
            ["O_ACTOR"] = "committed suicide",
            ["S_ACTOR"] = "committed suicide",
            ["AI_STL_S"] = "was gunned down by a stalker",
            ["AI_STL"] = "was gunned down by a stalker",
            ["SM_BLOOD"] = "was sucked dry by a bloodsucker",
            ["SM_BOARW"] = "was goared by a boar",
            ["SM_BURER"] = "met their fate at the hands of a burer",
            ["SM_CAT_S"] = "was scratched to death by a cat",
            ["SM_CHIMS"] = "was leapt on by a chimera",
            ["SM_CONTR"] = "was zombified by a controller",
            ["SM_DOG_S"] = "was mauled by a blind dog",
            ["SM_FLESH"] = "somehow died to a pig",
            ["SM_IZLOM"] = "was smashed by an izlom",
            ["SM_GIANT"] = "was crushed by a pseudogiant",
            ["AI_PHANT"] = "succumbed to brain damage",
            ["SM_POLTR"] = "was killed by some invisible thing",
            ["SM_P_DOG"] = "was hunted down by a pseudodog",
            ["SM_DOG_P"] = "was overwhelmed by a psy dog",
            ["SM_DOG_F"] = "was overwhelmed by a psy dog",
            ["AI_RAT"] = "was eaten alive by rats",
            ["SM_SNORK"] = "was kicked to death by a snork",
            ["SM_TUSHK"] = "was gnawed to the bone by a tushkano",
            ["SM_ZOMBI"] = "had their brains eaten by a zombie",
            ["C_HLCP_S"] = "was shot down by a helicopter",
            ["SCRPTCAR"] = "became roadkill",
            ["ZS_MBALD"] = "walked right into an anomaly",
            ["ZS_GALAN"] = "was sucked into a vortex",
            ["ZS_MINCE"] = "was sucked into a vortex",
            ["ZS_RADIO"] = "stepped into an anomalous field",
            ["ZS_TORRD"] = "couldn't outrun a comet",
            ["ZS_BFUZZ"] = "got tangled up in a burnt fuzz",
            ["Z_MBALD"] = "triggered a land mine",
            ["Z_RADIO"] = "stepped into an anomalous field",
            //deaths["Z_ZONE"] = "cse_alife_anomalous_zone",
            ["Z_CFIRE"] = "tripped and fell into a campfire",
            ["Z_TORRID"] = "got burned up by a comet",
            //deaths["Z_RUSTYH"] = "cse_alife_zone_visual",
            ["Z_AMEBA"] = "got tangled up in a burnt fuzz",
            ["S_EXPLO"] = "was blown apart by an explosion",
            ["II_EXPLO"] = "was blown apart by an explosion",

            // NPC factions
            ["STALKER"] = "was gunned down by a loner",
            ["BANDIT"] = "was looted by a bandit",
            ["DOLG"] = "was removed by a Dutyer",
            ["FREEDOM"] = "was blazed by a Freedomer",
            ["ECOLOG"] = "was blind-sided by a scientist",
            ["KILLER"] = "was taken out by a mercenary",
            ["MONOLITH"] = "was purged by a cultist",
            ["ZOMBIED"] = "was blown away by a zombified stalker",
            ["ARENA_ENEMY"] = "lost in the Arena",
            ["CSKY"] = "was killed by the best faction",
            ["ARMY"] = "was shot down by the military",
        };

        private static Dictionary<string, List<string>> fNames = new Dictionary<string, List<string>>()
        {
            ["actor_bandit"] = new List<string>()
            {
                "Andryukha",
                "Arkasha",
                "Bodya",
                "Boryan",
                "Dimon",
                "Dimukha",
                "Felka",
                "Fimka",
                "Grishka",
                "Grishko",
                "Ilyukha",
                "Kolyan",
                "Kostyan",
                "Lekha",
                "Mikha",
                "Mikhal",
                "Mikhas",
                "Mitka",
                "Pavlukha",
                "Sanek",
                "Sashok",
                "Shurik",
                "Stepka",
                "Stepukha",
                "Temka",
                "Timokha",
                "Tokha",
                "Tolyan",
                "Vadya",
                "Vasek",
                "Vasyan",
                "Vetal",
                "Vityukha",
                "Vovan",
                "Yashka",
                "Yuras",
                "Zheka",
                "Zhorka",
            },
            ["actor_ecolog"] = new List<string>()
            {
                "Aleksandr",
                "Alexey",
                "Anatoly",
                "Andrey",
                "Anton",
                "Bohdan",
                "Dmitry",
                "Ivan",
                "Konstantin",
                "Oleg",
                "Roman",
                "Sergey",
                "Veniamin",
                "Vitaly",
                "Vladimir",
                "Yuri",
            },
            ["actor_stalker"] = new List<string>()
            {
                "Alex",
                "Anton",
                "Artem",
                "Arthur",
                "Bohdan",
                "Borka",
                "Borya",
                "Danko",
                "Danya",
                "Dennis",
                "Dima",
                "Dimka",
                "Dmitro",
                "Edik",
                "Egor",
                "Egorka",
                "Fedka",
                "Fedor",
                "Fedya",
                "Filka",
                "Filya",
                "Fima",
                "Gena",
                "Genka",
                "George",
                "Gleb",
                "Gosha",
                "Grisha",
                "Grishka",
                "Grishko",
                "Igorek",
                "Ilya",
                "Kiryukha",
                "Kolya",
                "Kostik",
                "Kostya",
                "Lenya",
                "Leshka",
                "Leva",
                "Lyonka",
                "Mark",
                "Matvei",
                "Max",
                "Misha",
                "Mishka",
                "Mitya",
                "Nik",
                "Nikita",
                "Oleg",
                "Pasha",
                "Pashka",
                "Petka",
                "Petro",
                "Petya",
                "Roma",
                "Romka",
                "Rostik",
                "Rus",
                "Rusik",
                "Sanek",
                "Sanya",
                "Savva",
                "Sema",
                "Semyon",
                "Serega",
                "Seva",
                "Sevka",
                "Shurik",
                "Slava",
                "Slavik",
                "Stepa",
                "Stepan",
                "Tima",
                "Timka",
                "Tolik",
                "Toshka",
                "Vadik",
                "Vadim",
                "Vadya",
                "Valera",
                "Valik",
                "Vanka",
                "Vanya",
                "Vaska",
                "Vasko",
                "Vasya",
                "Venya",
                "Vitalik",
                "Vitka",
                "Vitya",
                "Vlad",
                "Vova",
                "Vovka",
                "Yara",
                "Yarik",
                "Yasha",
                "Yashka",
                "Yurik",
                "Yurka",
                "Yurko",
                "Zhenka",
                "Zhenya",
                "Zhora",
            },
            ["actor_army"] = new List<string>()
            {
                "Captain",
                "Junior Lieutenant",
                "Junior Sergeant",
                "Lieutenant",
                "Master Sergeant",
                "Private",
                "Senior Lieutenant",
                "Senior Private",
                "Senior Sergeant",
                "Sergeant",
            },
        };

        private static Dictionary<string, List<string>> sNames = new Dictionary<string, List<string>>()
        {
            ["actor_bandit"] = new List<string>()
            {
                "Ace",
                "Antelope",
                "Arsonist",
                "Artist",
                "Aspic",
                "Banana",
                "Banker",
                "Baron",
                "Beast",
                "Beaver",
                "Bedbug",
                "Berserk",
                "Biscuit",
                "Bison",
                "Blind",
                "Bling-bling",
                "Boa",
                "Boar",
                "Bolt",
                "Bosun",
                "Boulder",
                "Bourbon",
                "Bourgeois",
                "Brigand",
                "Broken",
                "Bruise",
                "Bulldog",
                "Butcher",
                "Butterfingers",
                "Canary",
                "Champ",
                "Chapai",
                "Charcoal",
                "Chauffeur",
                "Cheat",
                "Chemist",
                "Chili",
                "Chisel",
                "Coach",
                "Conman",
                "Connoisseur",
                "Corpse",
                "Counselor",
                "Count",
                "Cranky",
                "Cripple",
                "Crony",
                "Crooked",
                "Cross",
                "Crosstie",
                "Crowbar",
                "Crucian",
                "Dead Duck",
                "Deadbeat",
                "Defunct",
                "Degree",
                "Drum",
                "Dynamite",
                "Ears",
                "Executioner",
                "Fatso",
                "Fiend",
                "Fierce",
                "Fist",
                "Flop",
                "Fubar",
                "Gangrene",
                "Gangster",
                "Genghis",
                "Ghoul",
                "Glitch",
                "Goblin",
                "Godfather",
                "Grabber",
                "Grater",
                "Gray",
                "Greyhound",
                "Grindstone",
                "Guerilla",
                "Hacker",
                "Hipster",
                "Hitman",
                "Hobo",
                "Homeboy",
                "Hotshot",
                "Humpback",
                "Jackstraw",
                "Jester",
                "Jiggers",
                "Joint",
                "Junk",
                "Kamikaze",
                "Khan",
                "Kicker",
                "Koschei",
                "Lame",
                "Leech",
                "Lethal",
                "Loaf",
                "Local",
                "Long John",
                "Loudmouth",
                "Maniac",
                "Mayhem",
                "Messenger",
                "Met",
                "Miser",
                "Monocle",
                "Moor",
                "Moose",
                "Nark",
                "Nickel",
                "Ninja",
                "Ox",
                "Pacifist",
                "Panadol",
                "Papa",
                "Pariah",
                "Patty",
                "Peddler",
                "Percher",
                "Pigmy",
                "Pimp",
                "Pirate",
                "Piston",
                "Player",
                "Prince",
                "Psycho",
                "Punk",
                "Rambo",
                "Rascal",
                "Rat",
                "Ravioli",
                "Razor",
                "Reefer",
                "Robust",
                "Rotten",
                "Savage",
                "Screw",
                "Shaven",
                "Shifter",
                "Shiv",
                "Shortstop",
                "Shovel",
                "Skew",
                "Slasher",
                "Slime",
                "Snot",
                "Sock",
                "Sparrow",
                "Spike",
                "Spy",
                "Squint",
                "Squire",
                "Strangler",
                "Stud",
                "Sturdy",
                "Tadpole",
                "Tails",
                "Tar",
                "Terminator",
                "Thief",
                "Tightwad",
                "Torn",
                "Toupee",
                "Tour Guide",
                "Tramp",
                "Trombone",
                "Trump",
                "Turd",
                "Tyrant",
                "Undertaker",
                "Unorthodox",
                "Veteran",
                "Warlock",
                "Woodpecker",
            },
            ["actor_ecolog"] = new List<string>()
            {
                "Alferov",
                "Andreev",
                "Antipin",
                "Balitsky",
                "Belyavin",
                "Blinov",
                "Bogomolov",
                "Chernodub",
                "Chirikov",
                "Dyakonov",
                "Erokhin",
                "Fadeev",
                "Feigelman",
                "Geshkenbein",
                "Ivchenko",
                "Kabanov",
                "Larin",
                "Ledentsov",
                "Manko",
                "Mironov",
                "Oganesyan",
                "Shilov",
                "Sinaev",
                "Spirin",
                "Steklov",
                "Stepanenko",
                "Vasilevich",
                "Zaikin",
                "Zakharov",
            },
            ["actor_stalker"] = new List<string>()
            {
                "Absolute",
                "Ace",
                "Ack-ack",
                "Agent",
                "Alert",
                "Alligator",
                "Ambassador",
                "Anaconda",
                "Anomaly",
                "Ant",
                "Antelope",
                "Arsonist",
                "Artist",
                "Ascetic",
                "Aspic",
                "Athlete",
                "Atrocious",
                "Aurochs",
                "Aviator",
                "Axe",
                "Baboon",
                "Banana",
                "Banker",
                "Barbarian",
                "Bard",
                "Baron",
                "Barrel",
                "Beancounter",
                "Beanpole",
                "Beast",
                "Beaver",
                "Bedbug",
                "Beekeeper",
                "Beetle",
                "Belly",
                "Berserk",
                "Bigtime",
                "Biscuit",
                "Bison",
                "Bitter",
                "Black",
                "Blind",
                "Bling-bling",
                "Blithe",
                "Boa",
                "Boar",
                "Bolt",
                "Bonaparte",
                "Bone",
                "Boot",
                "Booze",
                "Boss",
                "Bosun",
                "Boulder",
                "Bourbon",
                "Bourgeois",
                "Brainiac",
                "Brave",
                "Brawny",
                "Breech",
                "Breeder",
                "Brick",
                "Brigand",
                "Broken",
                "Brown Nose",
                "Brownie",
                "Bruise",
                "Bubble",
                "Buffer",
                "Bugeyed",
                "Bulkin",
                "Bulldog",
                "Bulldozer",
                "Bully",
                "Bumper",
                "Bureaucrat",
                "Burr",
                "Bush",
                "Butcher",
                "Butt",
                "Butterfingers",
                "Cabbage",
                "Cabby",
                "Cadet",
                "Caesar",
                "Canary",
                "Cap",
                "Captain",
                "Carbide",
                "Carpenter",
                "Cartridge",
                "Casanova",
                "Cat",
                "Champ",
                "Chance",
                "Chapaev",
                "Chapai",
                "Charcoal",
                "Chauffeur",
                "Cheat",
                "Chebur",
                "Cheburashka",
                "Chemist",
                "Chest",
                "Chief",
                "Chili",
                "Chilly",
                "Chingachgook",
                "Chipmunk",
                "Chisel",
                "Chopper",
                "Cider",
                "Claw",
                "Closet",
                "Clown",
                "Clumsy",
                "Coach",
                "Coalminer",
                "Cobra",
                "Cockroach",
                "Coffin",
                "Collar",
                "Coma",
                "Comanche",
                "Commodore",
                "Conman",
                "Connoisseur",
                "Cook",
                "Corpse",
                "Cossack",
                "Counselor",
                "Count",
                "Courier",
                "Cranky",
                "Crest",
                "Cripple",
                "Croc",
                "Crony",
                "Crooked",
                "Cross",
                "Crosstie",
                "Crowbar",
                "Crucian",
                "Crybaby",
                "Cynic",
                "Daddy",
                "Dancer",
                "Dandy",
                "Dead Duck",
                "Deadbeat",
                "Debater",
                "Defector",
                "Defunct",
                "Degree",
                "Deputy",
                "Dinosaur",
                "Diplomat",
                "Disciple",
                "Diver",
                "Doc",
                "Doctor",
                "Dolphin",
                "Dork",
                "Doughboy",
                "Doughnut",
                "Dragon",
                "Drum",
                "Drummer",
                "Dry",
                "Dude",
                "Duke",
                "Dumpling",
                "Dynamite",
                "Ears",
                "Elder",
                "Electrician",
                "Elephant",
                "Engine",
                "Ethnic",
                "Executioner",
                "Factor",
                "Falcon",
                "Fan",
                "Fang",
                "Fatso",
                "Ferret",
                "Fiend",
                "Fierce",
                "Fighter",
                "Fireball",
                "Firefighter",
                "Fist",
                "Five",
                "Flecked",
                "Flop",
                "Fog",
                "Forester",
                "Fortunate",
                "Friday",
                "Fubar",
                "Gadfly",
                "Gangrene",
                "Gangster",
                "Garlic",
                "Genghis",
                "Geologist",
                "Germ",
                "Ghoul",
                "Gigolo",
                "Gioconda",
                "Gladiator",
                "Glitch",
                "Globe",
                "Glue",
                "Gnat",
                "Goblin",
                "Godfather",
                "Goofy",
                "Goose",
                "Gopher",
                "Gouge",
                "Grabber",
                "Grandpa",
                "Grasshopper",
                "Grater",
                "Grave",
                "Gray",
                "Green",
                "Gremlin",
                "Grenade",
                "Greyhound",
                "Grice",
                "Grim",
                "Grindstone",
                "Guerilla",
                "Guest",
                "Gunpowder",
                "Gunsmith",
                "Hacker",
                "Haggler",
                "Hamster",
                "Hardware",
                "Hare",
                "Harsh",
                "Hatchet",
                "Hawk",
                "Healer",
                "Heathen",
                "Hedgehog",
                "Highlander",
                "Hipster",
                "Hitman",
                "Hobo",
                "Holey",
                "Homeboy",
                "Homer",
                "Horseman",
                "Hotshot",
                "Humpback",
                "Hybrid",
                "Icarus",
                "Ice",
                "Immortal",
                "Indian",
                "Ink",
                "Iron",
                "Iroquois",
                "Isotope",
                "Jackstraw",
                "Janitor",
                "Jester",
                "Jiggers",
                "Jogger",
                "Joint",
                "Judge",
                "Jumper",
                "June",
                "Junk",
                "Kagor",
                "Kamikaze",
                "Karma",
                "Key",
                "Khan",
                "Kicker",
                "King",
                "Knot",
                "Kolobok",
                "Koschei",
                "Kutuzov",
                "Lame",
                "Lamp",
                "Lax",
                "Leech",
                "Legal",
                "Legionnaire",
                "Lethal",
                "Lifesaver",
                "Loaf",
                "Local",
                "Lock",
                "Log Splitter",
                "Long John",
                "Lord",
                "Loser",
                "Loudmouth",
                "Loyal",
                "Lucky Bastard",
                "Lucky",
                "Machine",
                "Machinist",
                "Madera",
                "Mammoth",
                "Maniac",
                "Mantis",
                "Manul",
                "Marmot",
                "Martian",
                "Mason",
                "Master",
                "Mayhem",
                "Meany",
                "Mechanic",
                "Merc",
                "Merchant",
                "Messenger",
                "Met",
                "Milkman",
                "Miner",
                "Minesweeper",
                "Minnow",
                "Miser",
                "Moderator",
                "Monocle",
                "Moonshine",
                "Moor",
                "Moose",
                "Mopper-up",
                "Morel",
                "Mosquito",
                "Motor",
                "Mummer",
                "Muskrat",
                "Mutant",
                "Nail",
                "Narcissus",
                "Nark",
                "Native",
                "Necro",
                "Nelson",
                "Neptune",
                "Nerve",
                "Nickel",
                "Ninja",
                "Nocturnal",
                "Noodle",
                "Nozzle",
                "Nuisance",
                "Oldtimer",
                "Operator",
                "Orderly",
                "Oscar",
                "Owl",
                "Ox",
                "PI",
                "Pacifist",
                "Painter",
                "Panadol",
                "Papa",
                "Parachute",
                "Paranoia",
                "Pariah",
                "Pastor",
                "Pathfinder",
                "Patty",
                "Pebble",
                "Peddler",
                "Peewee",
                "Percher",
                "Phantom",
                "Pigmy",
                "Pilgrim",
                "Pilot",
                "Pimp",
                "Pinocchio",
                "Piranha",
                "Pirate",
                "Piston",
                "Pitman",
                "Plantain",
                "Player",
                "Plowman",
                "Poet",
                "Polkan",
                "Pond",
                "Porter",
                "Postman",
                "Priest",
                "Prince",
                "Professor",
                "Prometheus",
                "Prophet",
                "Proud",
                "Psycho",
                "Pump",
                "Punk",
                "Pushkin",
                "Putty",
                "Python",
                "Quack",
                "Quarterback",
                "Rabby",
                "Rack",
                "Rainbow",
                "Rambo",
                "Rascal",
                "Rasta",
                "Rat",
                "Raven",
                "Ravioli",
                "Razor",
                "Reactor",
                "Red",
                "Redhead",
                "Reefer",
                "Righteous",
                "Roach",
                "Robot",
                "Robust",
                "Rock",
                "Rocker",
                "Rocket",
                "Rod",
                "Rogue",
                "Romantic",
                "Rook",
                "Root",
                "Roquefort",
                "Rotten",
                "Round",
                "Rusty",
                "Ryazansky",
                "Saber",
                "Salesman",
                "Samurai",
                "Savage",
                "Scavenger",
                "Scholar",
                "Screw",
                "Scrub",
                "Scythe",
                "Scythian",
                "Secretary",
                "Shah",
                "Sham",
                "Shaman",
                "Shaven",
                "Sheep Herder",
                "Shepherd",
                "Sheriff",
                "Shifter",
                "Shiv",
                "Shortstop",
                "Shotgun",
                "Shovel",
                "Shrink",
                "Shtirlitz",
                "Sieve",
                "Simpleton",
                "Siniy",
                "Skeleton",
                "Skew",
                "Slasher",
                "Slime",
                "Slipper",
                "Slouch",
                "Smart Aleck",
                "Smoker",
                "Sniper",
                "Snot",
                "Sock",
                "Softie",
                "Sophomore",
                "Sorcerer",
                "Space",
                "Spade",
                "Spaghetti",
                "Sparks",
                "Sparrow",
                "Spider",
                "Spike",
                "Spine",
                "Sportsman",
                "Spy",
                "Squint",
                "Squire",
                "Stag",
                "Stallion",
                "Stiff",
                "Storyteller",
                "Stranger",
                "Strangler",
                "Strap",
                "Stud",
                "Student",
                "Stunt",
                "Sturdy",
                "Subzero",
                "Summertime",
                "Sweeper",
                "Swifty",
                "Tadpole",
                "Tail",
                "Tails",
                "Tar",
                "Tarantula",
                "Target",
                "Teflon",
                "Terminator",
                "Thief",
                "Thinker",
                "Thorn",
                "Thrush",
                "Thunder",
                "Tightwad",
                "Timesheet",
                "Tin Man",
                "Toadstool",
                "Tobacco",
                "Torn",
                "Toupee",
                "Tour Guide",
                "Tourist",
                "Trailblazer",
                "Tramp",
                "Transporter",
                "Trap",
                "Trigger",
                "Trombone",
                "Trooper ",
                "Trump",
                "Tuner",
                "Turd",
                "Turkey",
                "Tycoon",
                "Tyrant",
                "Uncle",
                "Undertaker",
                "Unorthodox",
                "Vacuum",
                "Vandal",
                "Verbal",
                "Veteran",
                "Viking",
                "Visitor",
                "Voldemort",
                "Voyager",
                "Warden",
                "Warlock",
                "Whip",
                "Whiskey",
                "Whist",
                "Whistle",
                "White",
                "Wind",
                "Witcher",
                "Woodpecker",
                "Workhorse",
                "Worm",
                "Zinger",
                "Zucchini",
            },
            ["actor_army"] = new List<string>()
            {
                "Abdurakhmanov",
                "Altynnik",
                "Andreychuk",
                "Andruschenko",
                "Anisiev",
                "Ardashev",
                "Babich",
                "Balan",
                "Baranov",
                "Baranovsky",
                "Barsak",
                "Bashakov",
                "Bashmakov",
                "Baul",
                "Beshevly",
                "Binoev",
                "Blinov",
                "Bobrov",
                "Bogdanov",
                "Boichenko",
                "Boiko",
                "Boldeskul",
                "Bondarev",
                "Borisov",
                "Brich",
                "Bronshtein",
                "Buryak",
                "Buturin",
                "Byalo",
                "Denisenko",
                "Dombrik",
                "Dotsenko",
                "Dovgalyuk",
                "Drozdush",
                "Dubenchuk",
                "Dudorov",
                "Duka",
                "Dumko",
                "Dunaev",
                "Dyklov",
                "Efremov",
                "Erofeev",
                "Futzin",
                "Galkin",
                "Ganzyuk",
                "Garkovenko",
                "Garkusha",
                "Gatzula",
                "Georgov",
                "Glebovsky",
                "Gnatyuk",
                "Goncharenko",
                "Gordienko",
                "Gorlevoy",
                "Gorokhin",
                "Goryunov",
                "Grebenko",
                "Grischuk",
                "Grishachev",
                "Gritzaenko",
                "Gritzay",
                "Gritzenkov",
                "Gubar",
                "Gunko",
                "Gurevich",
                "Ignatenko",
                "Ischuk",
                "Ivanov",
                "Izhenko",
                "Kandybabko",
                "Kapuka",
                "Kapustyanko",
                "Katz",
                "Kazakov",
                "Kazantsev",
                "Khaladze",
                "Kikabidze",
                "Kireev",
                "Koev",
                "Kolontar",
                "Kolontarev",
                "Kondratenko",
                "Korkin",
                "Korneev",
                "Kovalchuk",
                "Kozlov",
                "Kravchenko",
                "Krivda",
                "Krivokhatsky",
                "Kryga",
                "Kucheruk",
                "Kulchistky",
                "Kulchitsky",
                "Kuntsev",
                "Kurvitz",
                "Kushnarev",
                "Kuzmich",
                "Kuznetsov",
                "Kuzyakin",
                "Lavrik",
                "Lavrov",
                "Lisichansky",
                "Litvin",
                "Livshits",
                "Lymarenko",
                "Makarenko",
                "Maltsev",
                "Mamaev",
                "Mazepa",
                "Merzlayev",
                "Milchenko",
                "Mironyuk",
                "Mohrer",
                "Mostovoi",
                "Mukhamedov",
                "Muntyan",
                "Myskov",
                "Navrotsky",
                "Nepritsky",
                "Nikanorov",
                "Nikeshin",
                "Nikulin",
                "Nordiev",
                "Nosan",
                "Opolev",
                "Orlevich",
                "Orlov",
                "Petkevich",
                "Petrenko",
                "Petrov",
                "Plokhenko",
                "Podyachev",
                "Polyanin",
                "Poplavsky",
                "Popov",
                "Portnykh",
                "Prasolov",
                "Prokopenko",
                "Proskurin",
                "Protsenko",
                "Prudov",
                "Puchek",
                "Pustovar",
                "Rabinovich",
                "Radkevich",
                "Rezun",
                "Rodnyansky",
                "Rogoza",
                "Rotan",
                "Rublev",
                "Rudik",
                "Rusanov",
                "Rychagirsky",
                "Sagitov",
                "Savchenko",
                "Savchuk",
                "Scherbin",
                "Sedykh",
                "Sereda",
                "Sidorenko",
                "Sidorov",
                "Sinitzyn",
                "Siniy",
                "Skameika",
                "Slutsky",
                "Smelov",
                "Smoly",
                "Sorokin",
                "Statzura",
                "Stepchin",
                "Stychinsky",
                "Sviridov",
                "Sykula",
                "Tarnavsky",
                "Tatarchuk",
                "Timchuk",
                "Valentinov",
                "Vasiliev",
                "Veselov",
                "Vinogradov",
                "Volanchuk",
                "Volodar",
                "Voloshin",
                "Vorokhaev",
                "Vorontsov",
                "Vovnenko",
                "Vyushinsky",
                "Zabyagoda",
                "Zagorodnyuk",
                "Zakharin",
                "Zamosenchuk",
                "Zarubin",
                "Zhabenko",
                "Zhmyev",
                "Zhurakovsky",
                "Zinoviev",
                "Zolotar",
                "Zozo",
                "Zubarev",
                "Zubkov",
                "Zvonnitsky",
            },
        };
    }
}
